### PR TITLE
Keyboard: Add more outlines

### LINKED ISSUE #5: Keyboard hitbox not aligned with the texture
image
On the **open-computers-1.8.0** build from the [experimental builds section](https://nightly.link/lucsoft/OpenComputers/workflows/build/master-MC1.16/Artifacts) there is a problem when you place down keyboards near the side or on the side of a block the texture is on the wall and the hit box is on the top of the block below the texture. It can also float there when there is no block below for the hit box to be attached to.

### PR DESCRIPTION
**Pull request by omixann**
Fairly straightforward, although I haven't tacked the UP position of the keyboard. The changes are trivial, but the process of making this PR has helped me setup the dev environment.

### CODE REVIEW

**Comment by lucsoft** [comment]
Thanks for the pull request i make a review when you added a switch case for the "pitch" states :)

**Comment by lucsoft** [comment]
Fix for #5

**Comment by omixann** [comment]
> 
> 
> Thanks for the pull request i make a review when you added a switch case for the "pitch" states :)

Done! It stood my rudimentary test (placing lots of keyboards in lots of orientations). Placement is glitched, but that's out of scope

**Review by lucsoft — APPROVED** [review]
LGTM, i will fix that the yaw is opposite after the merge

**Pull request merged**
